var data = [
	{
		name:'我的音乐',
		file_type:'floder',
		Pid:0,
		id:1,
		time:'2017.01.03',
		child:[
			{
				name:'南方姑娘',
				file_type:'audio/mpeg',
				src:'music/南方姑娘.mp3',
				img:'pic/4.jpg',
				time:'2017.03.05',
				Pid:1,
				id:1,
				child:[]
			},
			{
				name:'刚好遇见你-李玉刚',
				file_type:'audio/mpeg',
				src:'music/刚好遇见你.mp3',
				img:'pic/2.jpg',
				time:'2017.01.10',
				Pid:1,
				id:2,
				child:[]
			},
			{
				name:'告白气球-周杰伦',
				file_type:'audio/mpeg',
				src:'music/告白气球.mp3',
				img:'pic/3.jpg',
				time:'2017.01.20',
				Pid:1,
				id:3,
				child:[]
			}
		]
	},
	{
		name:'我的文档',
		file_type:'floder',
		time:'2017.01.05',
		Pid:0,
		id:2,
		child:[
			{
				name:'微云策划案',
				file_type:'application/msword',
				time:'2017.01.15',
				Pid:2,
				id:1,
				child:[]
			},
			{
				name:'微云列表',
				file_type:'application/msexcel',
				time:'2017.01.06',
				Pid:2,
				id:2,
				child:[]
			},
			{
				name:'微云演示文档',
				file_type:'application/vnd.ms-powerpoint',
				time:'2017.01.10',
				Pid:2,
				id:3,
				child:[]
			}
		]
	},
	{
		name:'QQ',
		file_type:'floder',
		time:'2017.02.03',
		Pid:0,
		id:3,
		child:[
			{
				name:'我的图片',
				file_type:'floder',
				time:'2017.02.01',
				child:[
					{
						name:'第二张专辑',
						file_type:'image/jpeg',
						src:'pic/1.jpg',
						time:'2017.01.05',
						Pid:3,
						id:1,
						child:[]
					},
					{
						name:'第三张专辑',
						file_type:'image/jpeg',
						src:'pic/2.jpg',
						time:'2017.01.10',
						Pid:3,
						id:2,
						child:[]
					}
				]
			},
			{
				name:'我的笔记',
				file_type:'floder',
				time:'2017.01.24',
				Pid:0,
				id:4,
				child:[
					{
						name:'游戏攻略',
						file_type:'text/plain',
						time:'2017.01.21',
						Pid:4,
						id:1,
						child:[]
					},
					{
						name:'美食',
						file_type:'text/plain',
						time:'2017.01.24',
						Pid:4,
						id:2,
						child:[]
					}
				]
			}
		]
	},
	{
		name:'群共享文件',
		file_type:'floder',
		time:'2017.02.05',
		Pid:0,
		id:5,
		child:[]
	},
	{
		name:'第一张专辑',
		file_type:'image/jpeg',
		src:'pic/jay.jpg',
		time:'2017.02.16',
		Pid:0,
		id:6,
		child:[]
	},
	{
		name:'旅游攻略',
		file_type:'text/plain',
		time:'2017.02.18',
		Pid:0,
		id:7,
		child:[]
	},
	{
		name:'成都-赵雷',
		file_type:'audio/mpeg',
		src:'music/成都.mp3',
		img:'pic/1.jpg',
		time:'2017.02.14',
		Pid:0,
		id:8,
		child:[]
	}
];
